"-",
":",
"?",
"??",
"???",
"????",
"?????",
"??????",
"???????",
"????????",
"?????????",
"??????????",
"???????????",
"????????????",
"?????????????",
"??????????????",
"???????????????",
"????????????????",
"?????????????????",
"??????????????????",
"???????????????????",
"????????????????????",
"?????????????????????",
"a",
"about",
"al",
"an",
"and",
"aquest",
"are",
"as",
"by",
"cada",
"como",
"commons",
"con",
"course",
"creative",
"curs",
"curso",
"de",
"del",
"desde",
"e",
"el",
"ellos",
"en",
"entre",
"es",
"eso",
"estos",
"for",
"forma",
"fuente",
"habia",
"hasta",
"i",
"in",
"is",
"la",
"las",
"le",
"les",
"lo",
"los",
"mas",
"my",
"no",
"o",
"of",
"on",
"para",
"pero",
"per",
"por",
"que",
"se",
"ser",
"sera",
"son",
"su",
"sus",
"tambien",
"that",
"the",
"this",
"to",
"tu",
"tras",
"un",
"una",
"we",
"will",
"with",
"y",
"ya",
"you"